apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: caller-service-app
  namespace: microservices
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: caller-service-app
  service:
    port: 8153
    targetPort: 8153
    name: caller-server-svc
  analysis:
    interval: 1m
    threshold: 10
    maxWeight: 50
    stepWeight: 10
