spring.kafka.bootstrap-servers=localhost:29092
spring.data.redis.host:localhost
spring.data.redis.port:6379

RESPONSE_SERVER_SVC= localhost

response.service.url= http://localhost:8154/response

logging.level.in.co= DEBUG